/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlRouteImport } from './routes/_pl'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as PlRenowacjaIndexRouteImport } from './routes/_pl/renowacja/index'
import { Route as PlKonstrukcjeIndexRouteImport } from './routes/_pl/konstrukcje/index'
import { Route as LangRenowacjaIndexRouteImport } from './routes/$lang/renowacja/index'
import { Route as LangKonstrukcjeIndexRouteImport } from './routes/$lang/konstrukcje/index'

const PlRoute = PlRouteImport.update({
  id: '/_pl',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const PlRenowacjaIndexRoute = PlRenowacjaIndexRouteImport.update({
  id: '/renowacja/',
  path: '/renowacja/',
  getParentRoute: () => PlRoute,
} as any)
const PlKonstrukcjeIndexRoute = PlKonstrukcjeIndexRouteImport.update({
  id: '/konstrukcje/',
  path: '/konstrukcje/',
  getParentRoute: () => PlRoute,
} as any)
const LangRenowacjaIndexRoute = LangRenowacjaIndexRouteImport.update({
  id: '/renowacja/',
  path: '/renowacja/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangKonstrukcjeIndexRoute = LangKonstrukcjeIndexRouteImport.update({
  id: '/konstrukcje/',
  path: '/konstrukcje/',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/konstrukcje/': typeof LangKonstrukcjeIndexRoute
  '/$lang/renowacja/': typeof LangRenowacjaIndexRoute
  '/konstrukcje/': typeof PlKonstrukcjeIndexRoute
  '/renowacja/': typeof PlRenowacjaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/konstrukcje': typeof LangKonstrukcjeIndexRoute
  '/$lang/renowacja': typeof LangRenowacjaIndexRoute
  '/konstrukcje': typeof PlKonstrukcjeIndexRoute
  '/renowacja': typeof PlRenowacjaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/_pl': typeof PlRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/konstrukcje/': typeof LangKonstrukcjeIndexRoute
  '/$lang/renowacja/': typeof LangRenowacjaIndexRoute
  '/_pl/konstrukcje/': typeof PlKonstrukcjeIndexRoute
  '/_pl/renowacja/': typeof PlRenowacjaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/konstrukcje/'
    | '/$lang/renowacja/'
    | '/konstrukcje/'
    | '/renowacja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/konstrukcje'
    | '/$lang/renowacja'
    | '/konstrukcje'
    | '/renowacja'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/_pl'
    | '/$lang/'
    | '/$lang/konstrukcje/'
    | '/$lang/renowacja/'
    | '/_pl/konstrukcje/'
    | '/_pl/renowacja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  PlRoute: typeof PlRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pl': {
      id: '/_pl'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/_pl/renowacja/': {
      id: '/_pl/renowacja/'
      path: '/renowacja'
      fullPath: '/renowacja/'
      preLoaderRoute: typeof PlRenowacjaIndexRouteImport
      parentRoute: typeof PlRoute
    }
    '/_pl/konstrukcje/': {
      id: '/_pl/konstrukcje/'
      path: '/konstrukcje'
      fullPath: '/konstrukcje/'
      preLoaderRoute: typeof PlKonstrukcjeIndexRouteImport
      parentRoute: typeof PlRoute
    }
    '/$lang/renowacja/': {
      id: '/$lang/renowacja/'
      path: '/renowacja'
      fullPath: '/$lang/renowacja/'
      preLoaderRoute: typeof LangRenowacjaIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/konstrukcje/': {
      id: '/$lang/konstrukcje/'
      path: '/konstrukcje'
      fullPath: '/$lang/konstrukcje/'
      preLoaderRoute: typeof LangKonstrukcjeIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangKonstrukcjeIndexRoute: typeof LangKonstrukcjeIndexRoute
  LangRenowacjaIndexRoute: typeof LangRenowacjaIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangKonstrukcjeIndexRoute: LangKonstrukcjeIndexRoute,
  LangRenowacjaIndexRoute: LangRenowacjaIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface PlRouteChildren {
  PlKonstrukcjeIndexRoute: typeof PlKonstrukcjeIndexRoute
  PlRenowacjaIndexRoute: typeof PlRenowacjaIndexRoute
}

const PlRouteChildren: PlRouteChildren = {
  PlKonstrukcjeIndexRoute: PlKonstrukcjeIndexRoute,
  PlRenowacjaIndexRoute: PlRenowacjaIndexRoute,
}

const PlRouteWithChildren = PlRoute._addFileChildren(PlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  PlRoute: PlRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
