/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DrewnoRouteImport } from './routes/drewno'
import { Route as CzyszczenieRouteImport } from './routes/czyszczenie'
import { Route as IndexRouteImport } from './routes/index'

const DrewnoRoute = DrewnoRouteImport.update({
  id: '/drewno',
  path: '/drewno',
  getParentRoute: () => rootRouteImport,
} as any)
const CzyszczenieRoute = CzyszczenieRouteImport.update({
  id: '/czyszczenie',
  path: '/czyszczenie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/czyszczenie': typeof CzyszczenieRoute
  '/drewno': typeof DrewnoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/czyszczenie': typeof CzyszczenieRoute
  '/drewno': typeof DrewnoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/czyszczenie': typeof CzyszczenieRoute
  '/drewno': typeof DrewnoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/czyszczenie' | '/drewno'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/czyszczenie' | '/drewno'
  id: '__root__' | '/' | '/czyszczenie' | '/drewno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CzyszczenieRoute: typeof CzyszczenieRoute
  DrewnoRoute: typeof DrewnoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drewno': {
      id: '/drewno'
      path: '/drewno'
      fullPath: '/drewno'
      preLoaderRoute: typeof DrewnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/czyszczenie': {
      id: '/czyszczenie'
      path: '/czyszczenie'
      fullPath: '/czyszczenie'
      preLoaderRoute: typeof CzyszczenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CzyszczenieRoute: CzyszczenieRoute,
  DrewnoRoute: DrewnoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
